name:  GBR 
on: 
 push:
   branches:
     - 'g1'
   paths:
     - 'go2/**'
   tags:
     - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.5

      - name: Install dependencies
        run: go mod tidy

      - name: Build application
        run: go build -o sc1

      - name: Run tests
        run: go test ./...

      - name: Conditional Release
        if: ${{ github.ref == 'refs/heads/g1' && startsWith(github.event_path, 'go2/') }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: jojop
          release_name: jojo
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          tag_name: joj
          release_name: jojo
          with:
            name: Release Artifact
            path: your_directory/
            if-no-files-found: error
            artifact-name: release-artifact-${{ steps.semantic_version.outputs.version }}
            retention-days: 7
            glob-pattern: '**'

jobs:
  CreateRelease:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go2

