name: GBR

on:
  push:
    branches:
      - g1
    paths:
     - 'go2/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.5

      - name: Install dependencies
        run: go mod tidy

      - name: Build application
        run: go build -o sc1

      - name: Run tests
        run: go test ./...

