name: GoBuild

on:
  push:
    branches:
      - 'g1'
    paths:
      - 'go2/**'

jobs:
  build:

    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: go2
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'
    
      - name: InstallDeps
        run: go mod tidy
        
      - name: Build
        run: go build -v

  release-linux-amd64:
    needs:
      - build
    name: release linux/amd64
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: go2/
    steps:
      - uses: actions/checkout@v3
        with:
          ref: g1  # Specify the branch name
          path: go2/  # Specify the directory
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
        