name: GoBuild

on:
  push:
    branches:
      - 'g1'
    paths:
      - 'go2/**'

jobs:
  build:

    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: go2
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'
    
      - name: InstallDeps
        run: go mod tidy
        

      - name: Build
        run: go build -v ./...

  CreateRelease:
    needs: 
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "sc1"

