name: GoBuild

on:
  push:
    branches:
      - 'g1'
    paths:
      - 'go2/**'

jobs:
  build:

    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'
    
      - name: InstallDeps
        run: go mod tidy
        working-directory: ./go2
        
      - name: Build
        run: go build -v
        working-directory: ./go2

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: '*'


  