on:
  push:
    branches:
      - g1
    paths:
      - 'go2/**'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ steps.semantic_version.outputs.version }}
          release_name: Release v${{ steps.semantic_version.outputs.version }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          tag_name: v${{ steps.semantic_version.outputs.version }}
          release_name: Release v${{ steps.semantic_version.outputs.version }}

      - name: Generate Semantic Version
        id: semantic_version
        uses: einaregilsson/semantic-version@v1
        with:
          bump: minor
          tag-prefix: v
